apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  mountOptions:
    - nfsvers=3
  nfs:
    server: 192.168.1.117
    path: /volume1/jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-static
  volumeName: nfs-config-pv
